# Generated by Django 2.0.2 on 2019-08-02 13:29

import ckeditor.fields
from django.db import migrations, models
import sd_secure.config


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('user', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=1000)),
                ('is_phone_verify', models.BooleanField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('termination_date', models.DateField(null=True)),
                ('send_date', models.DateField(null=True)),
                ('signature', models.ImageField(blank=True, max_length=255, upload_to=sd_secure.config.signature_directory_path)),
                ('status', models.CharField(default='deactivate', max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('document', ckeditor.fields.RichTextField()),
                ('field_value_pair', models.TextField()),
            ],
            options={
                'db_table': 'songdew_agreement_CreatedAgreement',
                'permissions': (('view_createdagreement', 'Can view songdew created agreement'),),
            },
        ),
        migrations.CreateModel(
            name='MasterAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('agreement_content', ckeditor.fields.RichTextField(default=False)),
                ('editfields', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'songdew_agreement_MasterAgreement',
                'permissions': (('view_masteragreement', 'Can view songdew master agreement'),),
            },
        ),
    ]
