# Generated by Django 2.0.2 on 2019-08-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdagreement',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
