# Generated by Django 2.0.2 on 2019-08-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0002_createdagreement_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdagreement',
            name='phone',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
