# Generated by Django 2.0.2 on 2019-08-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0003_auto_20190806_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdagreement',
            name='receiver_ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='createdagreement',
            name='sender_ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
